### ISSUE TITLE
Logged In - User Home Page - Default

### ISSUE THREAD

**Issue by theuxyeti** [theuxyeti/SugarSteem#6]
![logged in user home page viii list view default](https://user-images.githubusercontent.com/36086326/37945050-2e242daa-3133-11e8-8718-45f649b5f22b.png)

Once you have logged in id like you to come to this page by default. list view defaults. and you are defaulted to "my feed".

**Comment by r351574nc3** [comment]
This seems like a duplicate of #10 but with a different mockup. They're both default views and feeds for a logged in user.

**Comment by theuxyeti** [comment]
Unsure what your looking at but there’s only one default view as a logged in user and it’s the list view not the tile view

**Comment by theuxyeti** [comment]
This issue was moved to SugarSteem/SugarSteem#12
